// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2115/D 2900
// https://codeforces.com/problemset/status/2115/problem/D?friends=on
func Test_cf2115D(t *testing.T) {
	testCases := [][2]string{
		{
			`5
1
0
2
0
2
12 2
13 3
11
3
6 1 2
6 2 3
010
4
1 12 7 2
4 14 4 2
0111
9
0 5 10 6 6 2 6 2 11
7 3 15 3 6 7 6 7 8
110010010`,
			`0
15
6
11
5`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2115D)
}
