// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2154/D 1900
// https://codeforces.com/problemset/status/2154/problem/D?friends=on
func Test_cf2154D(t *testing.T) {
	testCases := [][2]string{
		{
			`4
5
1 2
2 3
1 5
5 4
2
1 2
4
1 2
1 3
1 4
6
1 2
1 3
3 4
4 5
4 6`,
			`2
2 2
1

1
1

5
2 2
1
1
2 3
1

9
2 2
1
2 1
1
2 3
1
1
2 5
1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2154D)
}
