// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/733/E 2400
// https://codeforces.com/problemset/status/733/problem/E?friends=on
func Test_cf733E(t *testing.T) {
	testCases := [][2]string{
		{
			`3
UUD`,
			`5 6 3`,
		},
		{
			`10
UUDUDUUDDU`,
			`5 12 23 34 36 27 18 11 6 1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf733E)
}
