// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2027/E1 2800
// https://codeforces.com/problemset/status/2027/problem/E1?friends=on
func Test_cf2027E1(t *testing.T) {
	testCases := [][2]string{
		{
			`7
2
1 6
10 7
3
10 8 15
25 4 14
4
8 32 65 64
7 45 126 94
3
20 40 1
23 55 1
5
12345 9876 86419 8641 1
6789 54321 7532 97532 1
2
20 64
44 61
3
57 109 55
69 90 85`,
			`Bob
Bob
Bob
Bob
Bob
Alice
Alice`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2027E1)
}
