// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2040/D 1900
// https://codeforces.com/problemset/status/2040/problem/D?friends=on
func Test_cf2040D(t *testing.T) {
	testCases := [][2]string{
		{
			`2
5
1 2
2 3
2 4
3 5
7
1 2
1 3
2 4
3 5
3 6
3 7`,
			`2 10 1 6 5 
8 7 12 1 4 6 3`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2040D)
}
