// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2045/F 3000
// https://codeforces.com/problemset/status/2045/problem/F?friends=on
func Test_cf2045F(t *testing.T) {
	testCases := [][2]string{
		{
			`3
2 2 4
1 1 3
2 1 2
100 2 1
4 1 10
4 4 10
10 5 2
1 1 4
3 1 2
4 2 5
2 2 1
5 3 4`,
			`Anda
Kamu
Anda`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2045F)
}
