// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/585/E 2900
// https://codeforces.com/problemset/status/585/problem/E?friends=on
func Test_cf585E(t *testing.T) {
	testCases := [][2]string{
		{
			`3
2 3 2`,
			`5`,
		},
		{
			`2
9 6`,
			`0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf585E)
}
