// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1739/B 1100
// https://codeforces.com/problemset/status/1739/problem/B?friends=on
func Test_cf1739B(t *testing.T) {
	testCases := [][2]string{
		{
			`3
4
1 0 2 5
3
2 6 3
5
0 0 0 0 0`,
			`1 1 3 8
-1
0 0 0 0 0`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1739B)
}
