// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1740/F 2600
// https://codeforces.com/problemset/status/1740/problem/F?friends=on
func Test_cf1740F(t *testing.T) {
	testCases := [][2]string{
		{
			`6
1 1 2 1 4 3`,
			`7`,
		},
		{
			`7
3 5 4 3 7 4 5`,
			`11`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1740F)
}
