// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1750/F 2700
// https://codeforces.com/problemset/status/1750/problem/F?friends=on
func Test_cf1750F(t *testing.T) {
	testCases := [][2]string{
		{
			`2 100`,
			`1`,
		},
		{
			`3 10`,
			`2`,
		},
		{
			`4 3271890`,
			`4`,
		},
		{
			`17 123456`,
			`32347`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1750F)
}
