// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1753/A2 1500
// https://codeforces.com/problemset/status/1753/problem/A2?friends=on
func Test_cf1753A2(t *testing.T) {
	testCases := [][2]string{
		{
			`5
4
0 0 0 0
7
-1 1 0 1 0 1 0
5
0 -1 1 0 1
3
1 0 1
1
1`,
			`4
1 1
2 2
3 3
4 4
4
1 1
2 2
3 5
6 7
-1
2
1 1
2 3
-1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1753A2)
}
