// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1781/F 2700
// https://codeforces.com/problemset/status/1781/problem/F?friends=on
func Test_cf1781F(t *testing.T) {
	testCases := [][2]string{
		{
			`1 7500`,
			`249561089`,
		},
		{
			`2 6000`,
			`519087064`,
		},
		{
			`5 4000`,
			`119387743`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1781F)
}
