// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/407/C 2500
// https://codeforces.com/problemset/status/407/problem/C?friends=on
func Test_cf407C(t *testing.T) {
	testCases := [][2]string{
		{
			`5 1
0 0 0 0 0
1 5 0`,
			`1 1 1 1 1`,
		},
		{
			`10 2
1 2 3 4 5 0 0 0 0 0
1 6 1
6 10 2`,
			`2 4 6 8 10 7 3 6 10 15`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf407C)
}
