// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1995/C 1800
// https://codeforces.com/problemset/status/1995/problem/C?friends=on
func Test_cf1995C(t *testing.T) {
	testCases := [][2]string{
		{
			`7
3
1 2 3
2
3 2
3
3 1 5
4
1 1 2 3
3
4 3 2
9
16 2 4 2 256 2 4 2 8
11
10010 10009 10008 10007 10006 10005 10004 10003 10002 10001 10000`,
			`0
1
-1
0
3
15
55`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1995C)
}
