// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1889/A 1300
// https://codeforces.com/problemset/status/1889/problem/A?friends=on
func Test_cf1889A(t *testing.T) {
	testCases := [][2]string{
		{
			`6
2
01
3
000
4
1111
6
001110
10
0111001100
3
001`,
			`0

-1
-1
2
6 7
1
10
-1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1889A)
}
